"""add_ai_enrichment

Revision ID: 1fafc7d82507
Revises: cfd37ce62863
Create Date: 2025-12-31 12:10:05.796748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1fafc7d82507'
down_revision: Union[str, Sequence[str], None] = 'cfd37ce62863'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scraped_data', sa.Column('ai_tags', sa.JSON(), nullable=True))
    op.add_column('scraped_data', sa.Column('ai_category', sa.String(length=100), nullable=True))
    op.add_column('scraped_data', sa.Column('ai_urgency', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scraped_data', 'ai_urgency')
    op.drop_column('scraped_data', 'ai_category')
    op.drop_column('scraped_data', 'ai_tags')
    # ### end Alembic commands ###
