"""Add rich content columns for trafilatura

Revision ID: 322c42237c96
Revises: 51677a572fd5
Create Date: 2025-12-29 09:23:46.409779

"""
from typing import Sequence, Union

from alembic import op # type: ignore
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '322c42237c96'
down_revision: Union[str, Sequence[str], None] = '51677a572fd5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scraped_data', sa.Column('author', sa.String(), nullable=True))
    op.add_column('scraped_data', sa.Column('published_date', sa.String(), nullable=True))
    op.add_column('scraped_data', sa.Column('summary', sa.Text(), nullable=True))
    op.add_column('scraped_data', sa.Column('main_image', sa.String(), nullable=True))
    op.add_column('scraped_data', sa.Column('clean_text', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scraped_data', 'clean_text')
    op.drop_column('scraped_data', 'main_image')
    op.drop_column('scraped_data', 'summary')
    op.drop_column('scraped_data', 'published_date')
    op.drop_column('scraped_data', 'author')
    # ### end Alembic commands ###
